[colors]
accent = '#95A328FF'
accent_secondary = '#95A328FF'
background = '#151515FF'
base00 = '#151515FF'
base01 = '#B44242FF'
base02 = '#95A328FF'
base03 = '#E1C135FF'
base04 = '#60928FFF'
base05 = '#7C435AFF'
base06 = '#A48B4AFF'
base07 = '#C2C2B0FF'
base08 = '#3F3639FF'
base09 = '#DC7671FF'
base0A = '#E8E85AFF'
base0B = '#9E9052FF'
base0C = '#76C39BFF'
base0D = '#86596CFF'
base0E = '#CEB34FFF'
base0F = '#B0AFA8FF'
border = '#3F3639FF'
border_focused = '#E1C135FF'
cursor = '#E1C135FF'
# Editor - Basic
editor_background = '#151515FF'
editor_foreground = '#C2C2B0FF'
editor_line_highlight = '#1C1C1CFF'
editor_selection = '#3F3639FF'
editor_selection_inactive = '#2A2A2AFF'
editor_cursor = '#E1C135FF'
editor_whitespace = '#3F3639FF'

# Editor - Gutter
editor_gutter_background = '#151515FF'
editor_gutter_foreground = '#7A7A7AFF'
editor_line_number = '#86596CFF'
editor_line_number_active = '#C2C2B0FF'

# Editor - Syntax
editor_comment = '#7A7A7AFF'
editor_string = '#76C39BFF'
editor_number = '#DC7671FF'
editor_boolean = '#DC7671FF'
editor_keyword = '#CEB34FFF'
editor_operator = '#C2C2B0FF'
editor_function = '#95A328FF'
editor_variable = '#C2C2B0FF'
editor_parameter = '#60928FFF'
editor_property = '#76C39BFF'
editor_constant = '#DC7671FF'
editor_type = '#60928FFF'
editor_class = '#60928FFF'
editor_interface = '#60928FFF'
editor_enum = '#60928FFF'
editor_namespace = '#86596CFF'
editor_attribute = '#E1C135FF'
editor_decorator = '#E1C135FF'
editor_tag = '#B44242FF'
editor_punctuation = '#B0AFA8FF'
editor_link = '#60928FFF'
editor_regex = '#CEB34FFF'
editor_escape_character = '#DC7671FF'

# Editor - Diagnostics
editor_invalid = '#B44242FF'
editor_error = '#B44242FF'
editor_error_background = '#2A1515FF'
editor_warning = '#E1C135FF'
editor_warning_background = '#2A2515FF'
editor_info = '#60928FFF'
editor_info_background = '#15252AFF'
editor_hint = '#95A328FF'
editor_hint_background = '#1A2A15FF'

# Editor - UI Elements
editor_active_line_border = '#3F3639FF'
editor_indent_guide = '#2A2A2AFF'
editor_indent_guide_active = '#3F3639FF'
editor_bracket_match = '#E1C135FF'
editor_search_match = '#E1C13580'
editor_search_match_active = '#E1C135FF'
editor_find_range_highlight = '#E1C13540'

# Editor - Diff
editor_deleted = '#B44242FF'
editor_inserted = '#95A328FF'
editor_modified = '#E1C135FF'
editor_ignored = '#7A7A7AFF'
editor_folded_background = '#1C1C1CFF'
error = '#B44242FF'
foreground = '#C2C2B0FF'
info = '#60928FFF'
on_background = '#C2C2B0FF'
on_error = '#151515FF'
on_info = '#151515FF'
on_success = '#151515FF'
on_surface = '#C2C2B0FF'
on_surface_variant = '#CCCCCCFF'
on_warning = '#151515FF'
success = '#95A328FF'
surface = '#1C1C1CFF'
surface_variant = '#1C1C1CFF'
warning = '#E1C135FF'

[general]
name = 'cursed'