[colors]
accent = '#9A8652FF'
accent_secondary = '#9A8652FF'
background = '#111111FF'
base00 = '#111111FF'
base01 = '#668A51FF'
base02 = '#9A8652FF'
base03 = '#B47837FF'
base04 = '#9A5552FF'
base05 = '#AA477BFF'
base06 = '#3A898CFF'
base07 = '#B5B5B5FF'
base08 = '#AA4E4AFF'
base09 = '#A9DC86FF'
base0A = '#B6AB82FF'
base0B = '#C5916BFF'
base0C = '#AC7676FF'
base0D = '#B0779EFF'
base0E = '#849899FF'
base0F = '#D2D2D2FF'
border = '#242424FF'
border_focused = '#2E2E2EFF'
cursor = '#D2D2D2FF'
# Editor - Basic
editor_background = '#111111FF'
editor_foreground = '#D2D2D2FF'
editor_line_highlight = '#191919FF'
editor_selection = '#242424FF'
editor_selection_inactive = '#1D1C1CFF'
editor_cursor = '#D2D2D2FF'
editor_whitespace = '#3A3A3AFF'

# Editor - Gutter
editor_gutter_background = '#111111FF'
editor_gutter_foreground = '#849899FF'
editor_line_number = '#849899FF'
editor_line_number_active = '#D2D2D2FF'

# Editor - Syntax
editor_comment = '#849899FF'
editor_string = '#9A8652FF'
editor_number = '#B47837FF'
editor_boolean = '#B47837FF'
editor_keyword = '#3A898CFF'
editor_operator = '#D2D2D2FF'
editor_function = '#A9DC86FF'
editor_variable = '#D2D2D2FF'
editor_parameter = '#B0779EFF'
editor_property = '#9A8652FF'
editor_constant = '#B47837FF'
editor_type = '#3A898CFF'
editor_class = '#3A898CFF'
editor_interface = '#3A898CFF'
editor_enum = '#3A898CFF'
editor_namespace = '#B0779EFF'
editor_attribute = '#A9DC86FF'
editor_decorator = '#A9DC86FF'
editor_tag = '#AA4E4AFF'
editor_punctuation = '#D2D2D2FF'
editor_link = '#B0779EFF'
editor_regex = '#AA477BFF'
editor_escape_character = '#B47837FF'

# Editor - Diagnostics
editor_invalid = '#AA4E4AFF'
editor_error = '#AA4E4AFF'
editor_error_background = '#3A1A1AFF'
editor_warning = '#B47837FF'
editor_warning_background = '#3A2A1AFF'
editor_info = '#3A898CFF'
editor_info_background = '#1A2A3AFF'
editor_hint = '#668A51FF'
editor_hint_background = '#1A2A1AFF'

# Editor - UI Elements
editor_active_line_border = '#2E2E2EFF'
editor_indent_guide = '#2A2A2AFF'
editor_indent_guide_active = '#3A3A3AFF'
editor_bracket_match = '#3A898CFF'
editor_search_match = '#9A865280'
editor_search_match_active = '#9A8652FF'
editor_find_range_highlight = '#9A865240'

# Editor - Diff
editor_deleted = '#AA4E4AFF'
editor_inserted = '#668A51FF'
editor_modified = '#9A8652FF'
editor_ignored = '#849899FF'
editor_folded_background = '#191919FF'
error = '#AA4E4AFF'
foreground = '#D2D2D2FF'
info = '#3A898CFF'
on_background = '#D4D4D4FF'
on_error = '#D2D2D2FF'
on_info = '#D2D2D2FF'
on_success = '#D2D2D2FF'
on_surface = '#D4D4D4FF'
on_surface_variant = '#D4D4D4FF'
on_warning = '#D2D2D2FF'
success = '#668A51FF'
surface = '#111111FF'
surface_variant = '#191919FF'
warning = '#B47837FF'

[general]
name = 'dark'