[colors]
accent = '#7FA5FFFF'
accent_secondary = '#A9DCFFFF'
background = '#090F1FFF'
base00 = '#090F1FFF'
base01 = '#293F82FF'
base02 = '#293F82FF'
base03 = '#293F82FF'
base04 = '#7FA5FFFF'
base05 = '#7FA5FFFF'
base06 = '#A9DCFFFF'
base07 = '#A9DCFFFF'
base08 = '#293F82FF'
base09 = '#663E41FF'
base0A = '#293F82FF'
base0B = '#293F82FF'
base0C = '#A9DCFFFF'
base0D = '#7FA5FFFF'
base0E = '#7FA5FFFF'
base0F = '#293F82FF'
border = '#293F82FF'
border_focused = '#7FA5FFFF'
cursor = '#A9DCFFFF'
editor_active_line_border = '#293F82FF'
editor_attribute = '#293F82FF'
editor_background = '#090F1FFF'
editor_boolean = '#293F82FF'
editor_bracket_match = '#A9DCFFFF'
editor_class = '#A9DCFFFF'
editor_comment = '#293F82FF'
editor_constant = '#293F82FF'
editor_cursor = '#A9DCFFFF'
editor_decorator = '#293F82FF'
editor_deleted = '#293F82FF'
editor_enum = '#A9DCFFFF'
editor_error = '#293F82FF'
editor_error_background = '#090F1FFF'
editor_escape_character = '#293F82FF'
editor_find_range_highlight = '#293F82FF'
editor_folded_background = '#293F82FF'
editor_foreground = '#A9DCFFFF'
editor_function = '#293F82FF'
editor_gutter_background = '#090F1FFF'
editor_gutter_foreground = '#293F82FF'
editor_hint = '#293F82FF'
editor_hint_background = '#090F1FFF'
editor_ignored = '#293F82FF'
editor_indent_guide = '#293F82FF'
editor_indent_guide_active = '#A9DCFFFF'
editor_info = '#7FA5FFFF'
editor_info_background = '#090F1FFF'
editor_inserted = '#293F82FF'
editor_interface = '#A9DCFFFF'
editor_invalid = '#293F82FF'
editor_keyword = '#7FA5FFFF'
editor_line_highlight = '#0C1234FF'
editor_line_number = '#293F82FF'
editor_line_number_active = '#A9DCFFFF'
editor_link = '#7FA5FFFF'
editor_modified = '#293F82FF'
editor_namespace = '#7FA5FFFF'
editor_number = '#293F82FF'
editor_operator = '#A9DCFFFF'
editor_parameter = '#7FA5FFFF'
editor_property = '#293F82FF'
editor_punctuation = '#A9DCFFFF'
editor_regex = '#7FA5FFFF'
editor_search_match = '#293F82FF'
editor_search_match_active = '#293F82FF'
editor_selection = '#0F1631FF'
editor_selection_inactive = '#0C1227FF'
editor_string = '#293F82FF'
editor_tag = '#293F82FF'
editor_type = '#A9DCFFFF'
editor_variable = '#A9DCFFFF'
editor_warning = '#293F82FF'
editor_warning_background = '#090F1FFF'
editor_whitespace = '#293F82FF'
error = '#293F82FF'
foreground = '#A9DCFFFF'
info = '#7FA5FFFF'
on_background = '#A9DCFFFF'
on_error = '#090F1FFF'
on_info = '#090F1FFF'
on_success = '#090F1FFF'
on_surface = '#A9DCFFFF'
on_surface_variant = '#A9DCFFFF'
on_warning = '#090F1FFF'
success = '#293F82FF'
surface = '#090F1FFF'
surface_variant = '#0F1631FF'
warning = '#293F82FF'

[general]
name = 'hellwal:wallhaven-7j9z3o.jpg'