[colors]
accent = '#9A8C98FF'
accent_secondary = '#C9ADA7FF'
background = '#0F0F1EFF'
base00 = '#0F0F1EFF'
base01 = '#D49384FF'
base02 = '#C9ADA7FF'
base03 = '#4A4E69FF'
base04 = '#9A8C98FF'
base05 = '#C9ADA7FF'
base06 = '#F2E9E4FF'
base07 = '#F2E9E4FF'
base08 = '#D16C8BFF'
base09 = '#C9ADA7FF'
base0A = '#D4C87DFF'
base0B = '#7EC87EFF'
base0C = '#9A8C98FF'
base0D = '#9A8C98FF'
base0E = '#C9ADA7FF'
base0F = '#F2E9E4FF'
border = '#22223BFF'
border_focused = '#4A4E69FF'
cursor = '#F2E9E4FF'
editor_background = '#0F0F1EFF'
editor_command = '#9A8C98FF'
editor_comment = '#4A4E69FF'
editor_disabled = '#4A4E69FF'
editor_emphasis = '#C9ADA7FF'
editor_error = '#D16C8BFF'
editor_inactive = '#4A4E69FF'
editor_line_number = '#9A8C98FF'
editor_link = '#9A8C98FF'
editor_main = '#F2E9E4FF'
editor_selected = '#9A8C98FF'
editor_selection_inactive = '#22223BFF'
editor_string = '#C9ADA7FF'
editor_success = '#7EC87EFF'
editor_warning = '#D4C87DFF'
error = '#D16C8BFF'
foreground = '#F2E9E4FF'
info = '#9A8C98FF'
on_background = '#F2E9E4FF'
on_error = '#F2E9E4FF'
on_info = '#F2E9E4FF'
on_success = '#0F0F1EFF'
on_surface = '#F2E9E4FF'
on_surface_variant = '#C9ADA7FF'
on_warning = '#0F0F1EFF'
success = '#7EC87EFF'
surface = '#1A1A2EFF'
surface_variant = '#22223BFF'
warning = '#D4C87DFF'

[general]
name = 'lavender'