[colors]
accent = '#9A8C98FF'
accent_secondary = '#C9ADA7FF'
background = '#0F0F1EFF'
base00 = '#0F0F1EFF'
base01 = '#D49384FF'
base02 = '#C9ADA7FF'
base03 = '#4A4E69FF'
base04 = '#9A8C98FF'
base05 = '#C9ADA7FF'
base06 = '#F2E9E4FF'
base07 = '#F2E9E4FF'
base08 = '#D16C8BFF'
base09 = '#C9ADA7FF'
base0A = '#D4C87DFF'
base0B = '#7EC87EFF'
base0C = '#9A8C98FF'
base0D = '#9A8C98FF'
base0E = '#C9ADA7FF'
base0F = '#F2E9E4FF'
border = '#22223BFF'
border_focused = '#3E3E65FF'
cursor = '#F2E9E4FF'
editor_active_line_border = '#2E2E2EFF'
editor_attribute = '#A9DC86FF'
editor_background = '#0F0F1EFF'
editor_boolean = '#B47837FF'
editor_bracket_match = '#3A898CFF'
editor_class = '#3A898CFF'
editor_comment = '#4A4E69FF'
editor_constant = '#B47837FF'
editor_cursor = '#D2D2D2FF'
editor_decorator = '#A9DC86FF'
editor_deleted = '#AA4E4AFF'
editor_enum = '#3A898CFF'
editor_error = '#D16C8BFF'
editor_error_background = '#3A1A1AFF'
editor_escape_character = '#B47837FF'
editor_find_range_highlight = '#9A865240'
editor_folded_background = '#191919FF'
editor_foreground = '#D2D2D2FF'
editor_function = '#A9DC86FF'
editor_gutter_background = '#111111FF'
editor_gutter_foreground = '#849899FF'
editor_hint = '#668A51FF'
editor_hint_background = '#1A2A1AFF'
editor_ignored = '#849899FF'
editor_indent_guide = '#2A2A2AFF'
editor_indent_guide_active = '#3A3A3AFF'
editor_info = '#3A898CFF'
editor_info_background = '#1A2A3AFF'
editor_inserted = '#668A51FF'
editor_interface = '#3A898CFF'
editor_invalid = '#AA4E4AFF'
editor_keyword = '#3A898CFF'
editor_line_highlight = '#191919FF'
editor_line_number = '#9A8C98FF'
editor_line_number_active = '#D2D2D2FF'
editor_link = '#9A8C98FF'
editor_modified = '#9A8652FF'
editor_namespace = '#B0779EFF'
editor_number = '#B47837FF'
editor_operator = '#D2D2D2FF'
editor_parameter = '#B0779EFF'
editor_property = '#9A8652FF'
editor_punctuation = '#D2D2D2FF'
editor_regex = '#AA477BFF'
editor_search_match = '#9A865280'
editor_search_match_active = '#9A8652FF'
editor_selection = '#242424FF'
editor_selection_inactive = '#22223BFF'
editor_string = '#C9ADA7FF'
editor_tag = '#AA4E4AFF'
editor_type = '#3A898CFF'
editor_variable = '#D2D2D2FF'
editor_warning = '#D4C87DFF'
editor_warning_background = '#3A2A1AFF'
editor_whitespace = '#3A3A3AFF'
error = '#D16C8BFF'
foreground = '#F2E9E4FF'
info = '#9A8C98FF'
on_background = '#F2E9E4FF'
on_error = '#F2E9E4FF'
on_info = '#F2E9E4FF'
on_success = '#0F0F1EFF'
on_surface = '#F2E9E4FF'
on_surface_variant = '#C9ADA7FF'
on_warning = '#0F0F1EFF'
success = '#7EC87EFF'
surface = '#1A1A2EFF'
surface_variant = '#22223BFF'
warning = '#D4C87DFF'

[general]
name = 'lavender'