[colors]
accent = '#9A8652FF'
accent_secondary = '#9A8652FF'
background = '#E0E0E0FF'
base00 = '#E0E0E0FF'
base01 = '#668A51FF'
base02 = '#9A8652FF'
base03 = '#B47837FF'
base04 = '#9A5552FF'
base05 = '#AA477BFF'
base06 = '#3A898CFF'
base07 = '#5A5A5AFF'
base08 = '#AA4E4AFF'
base09 = '#4A7A2EFF'
base0A = '#7A6A42FF'
base0B = '#A5714BFF'
base0C = '#8C5656FF'
base0D = '#90577EFF'
base0E = '#2A6A6DFF'
base0F = '#2A2A2AFF'
border = '#C5C5C5FF'
border_focused = '#B9B9B9FF'
cursor = '#2A2A2AFF'
# Editor - Basic
editor_background = '#E0E0E0FF'
editor_foreground = '#2A2A2AFF'
editor_line_highlight = '#D5D5D5FF'
editor_selection = '#C9C9C9FF'
editor_selection_inactive = '#D2D2D2FF'
editor_cursor = '#2A2A2AFF'
editor_whitespace = '#B0B0B0FF'

# Editor - Gutter
editor_gutter_background = '#E0E0E0FF'
editor_gutter_foreground = '#9A9A95FF'
editor_line_number = '#9A9A95FF'
editor_line_number_active = '#2A2A2AFF'

# Editor - Syntax
editor_comment = '#849899FF'
editor_string = '#9A8652FF'
editor_number = '#B47837FF'
editor_boolean = '#B47837FF'
editor_keyword = '#3A898CFF'
editor_operator = '#2A2A2AFF'
editor_function = '#4A7A2EFF'
editor_variable = '#2A2A2AFF'
editor_parameter = '#90577EFF'
editor_property = '#9A8652FF'
editor_constant = '#B47837FF'
editor_type = '#3A898CFF'
editor_class = '#3A898CFF'
editor_interface = '#3A898CFF'
editor_enum = '#3A898CFF'
editor_namespace = '#90577EFF'
editor_attribute = '#4A7A2EFF'
editor_decorator = '#4A7A2EFF'
editor_tag = '#AA4E4AFF'
editor_punctuation = '#2A2A2AFF'
editor_link = '#90577EFF'
editor_regex = '#AA477BFF'
editor_escape_character = '#B47837FF'

# Editor - Diagnostics
editor_invalid = '#AA4E4AFF'
editor_error = '#AA4E4AFF'
editor_error_background = '#FFDDDDFF'
editor_warning = '#B47837FF'
editor_warning_background = '#FFF0D0FF'
editor_info = '#3A898CFF'
editor_info_background = '#D0F0FFFF'
editor_hint = '#668A51FF'
editor_hint_background = '#D0FFD0FF'

# Editor - UI Elements
editor_active_line_border = '#C5C5C5FF'
editor_indent_guide = '#CFCFCFFF'
editor_indent_guide_active = '#B0B0B0FF'
editor_bracket_match = '#3A898CFF'
editor_search_match = '#9A865280'
editor_search_match_active = '#9A8652FF'
editor_find_range_highlight = '#9A865240'

# Editor - Diff
editor_deleted = '#AA4E4AFF'
editor_inserted = '#668A51FF'
editor_modified = '#9A8652FF'
editor_ignored = '#A0A0A0FF'
editor_folded_background = '#D5D5D5FF'
error = '#AA4E4AFF'
foreground = '#2A2A2AFF'
info = '#3A898CFF'
on_background = '#2A2A2AFF'
on_error = '#FAFAF8FF'
on_info = '#FAFAF8FF'
on_success = '#FAFAF8FF'
on_surface = '#2A2A2AFF'
on_surface_variant = '#3A3A3AFF'
on_warning = '#FAFAF8FF'
success = '#668A51FF'
surface = '#E0E0E0FF'
surface_variant = '#CECECEFF'
warning = '#B47837FF'

[general]
name = 'light'