[colors]
accent = '#A1CDFAFF'
accent_secondary = '#A1CDFAFF'
background = '#2E3440FF'
base00 = '#2E3440FF'
base01 = '#BF616AFF'
base02 = '#A3BE8CFF'
base03 = '#EBCB8BFF'
base04 = '#81A1C1FF'
base05 = '#B48EADFF'
base06 = '#88C0D0FF'
base07 = '#E5E9F0FF'
base08 = '#4C566AFF'
base09 = '#D08770FF'
base0A = '#EBCB8BFF'
base0B = '#A3BE8CFF'
base0C = '#8FBCBBFF'
base0D = '#5E81ACFF'
base0E = '#B48EADFF'
base0F = '#ECEFF4FF'
border = '#4C566AFF'
border_focused = '#88C0D0FF'
cursor = '#D8DEE9FF'
# Editor - Basic
editor_background = '#2E3440FF'
editor_foreground = '#D8DEE9FF'
editor_line_highlight = '#3B4252FF'
editor_selection = '#434C5EFF'
editor_selection_inactive = '#3B4252FF'
editor_cursor = '#D8DEE9FF'
editor_whitespace = '#4C566AFF'

# Editor - Gutter
editor_gutter_background = '#2E3440FF'
editor_gutter_foreground = '#4C566AFF'
editor_line_number = '#4C566AFF'
editor_line_number_active = '#D8DEE9FF'

# Editor - Syntax
editor_comment = '#616E88FF'
editor_string = '#A3BE8CFF'
editor_number = '#B48EADFF'
editor_boolean = '#B48EADFF'
editor_keyword = '#81A1C1FF'
editor_operator = '#D8DEE9FF'
editor_function = '#88C0D0FF'
editor_variable = '#D8DEE9FF'
editor_parameter = '#D8DEE9FF'
editor_property = '#8FBCBBFF'
editor_constant = '#B48EADFF'
editor_type = '#8FBCBBFF'
editor_class = '#8FBCBBFF'
editor_interface = '#8FBCBBFF'
editor_enum = '#8FBCBBFF'
editor_namespace = '#5E81ACFF'
editor_attribute = '#D08770FF'
editor_decorator = '#D08770FF'
editor_tag = '#BF616AFF'
editor_punctuation = '#ECEFF4FF'
editor_link = '#88C0D0FF'
editor_regex = '#EBCB8BFF'
editor_escape_character = '#D08770FF'

# Editor - Diagnostics
editor_invalid = '#BF616AFF'
editor_error = '#BF616AFF'
editor_error_background = '#3B2E2EFF'
editor_warning = '#EBCB8BFF'
editor_warning_background = '#3B3B2EFF'
editor_info = '#5E81ACFF'
editor_info_background = '#2E3440FF'
editor_hint = '#A3BE8CFF'
editor_hint_background = '#2E3B2EFF'

# Editor - UI Elements
editor_active_line_border = '#4C566AFF'
editor_indent_guide = '#3B4252FF'
editor_indent_guide_active = '#4C566AFF'
editor_bracket_match = '#88C0D0FF'
editor_search_match = '#EBCB8B80'
editor_search_match_active = '#EBCB8BFF'
editor_find_range_highlight = '#EBCB8B40'

# Editor - Diff
editor_deleted = '#BF616AFF'
editor_inserted = '#A3BE8CFF'
editor_modified = '#EBCB8BFF'
editor_ignored = '#616E88FF'
editor_folded_background = '#3B4252FF'
error = '#BF616AFF'
foreground = '#D8DEE9FF'
info = '#5E81ACFF'
on_background = '#D8DEE9FF'
on_error = '#2E3440FF'
on_info = '#2E3440FF'
on_success = '#2E3440FF'
on_surface = '#ECEFF4FF'
on_surface_variant = '#ECEFF4FF'
on_warning = '#2E3440FF'
success = '#A3BE8CFF'
surface = '#3B4252FF'
surface_variant = '#434C5EFF'
warning = '#EBCB8BFF'

[general]
name = 'nord'